### ISSUE TITLE
Submodule missing?

### ISSUE THREAD

**Issue by nelsonjchen** [markspit93/AutoTechno#1]
Is something supposed to be in the AutoTechno folder/submodule?

**Comment by markspit93** [comment]
I am not aware of such a folder. What is your issue exactly?

**Comment by nelsonjchen** [comment]
At the root of the Repository, there's a "AutoTechno" submodule.

<img width="1129" alt="screen shot 2018-07-31 at 11 56 20 am" src="https://user-images.githubusercontent.com/5363/43480734-f7f0a0b2-94b8-11e8-8c64-2cc0b92c3556.png">


Running `git submodule update --init` after cloning results in:

```
fatal: No url found for submodule path 'AutoTechno' in .gitmodules
```

**Comment by markspit93** [comment]
Now I understand what you mean. Its strange because, first off, I do not remember creating that submodule.
I doubled checked and I also get the same error when listing any submodules.
The app does not require anything else to run, so ignore it and just build the app.

I had tried using the Windows Github app when creating this repo, so it might have been a bug.
