### ISSUE TITLE
Favorites ability?

### ISSUE THREAD

**Issue by chs-bnet** [markspit93/AutoTechno#10]
It looks like this app doesn't actually hook into DI and your account settings in any way. I'd love the ability to either "star" channels directly in the app, therefore building a "favorites" list, or the ability for the app to just pull my existing "favorites" from my DI account/settings.

I listen to about a dozen different channels, and it's frustrating having to find them in their particular genre first. Half the time I'm not actually sure what the genre is I should be looking at to find them.

**Comment by markspit93** [comment]
I already have in mind to add a "Star" button which lets you add to a Favorites list.
Unfortunately, it will not be in sync with your DI.FM account.
They do not expose anything except for the listener key which, as the name suggests, is used to listen to radio channels only.

**Comment by chs-bnet** [comment]
Yeah, I kinda figured they didn't have a proper account settings/favorites API.

Having an in-app "favorites" would be awesome though! Thanks!

**Comment by crenier** [comment]
Mark, absolutely love this app -- I use it every day!

Any progress on the favorite list / 'star' functionality?
What would be handy too is an option that the last selected station would autoplay next time android auto is launched?

But in any case, thank you for making DI.FM possible trough Android Auto!!

**Comment by lwojcik** [comment]
Hi!

I recently switched to a car with Android Auto support and your app is an absolute godsend.

However, being able to have 'favorites' section (even if it's not in sync with my DI.FM settings) would be super helpful.

Alternatively, I'd be happy to have an option to resume recently played channel. Resuming audio in my Android Auto is far from consistent.

I'm kinda sad I'm a frontend developer and I can't into Java, otherwise I'd have sent a pull request for that. :(

**Comment by markspit93** [comment]
Hey guys, really sorry for the delay on this feature. Glad to say it is finally done :)
The favorites is now the first item in the main screen.
Whenever you 'star' a channel it will be added to this list.
